"""Add role column to User

Revision ID: 74af7b56fd88
Revises: b61fe73ced1b
Create Date: 2025-03-14 16:14:05.509818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74af7b56fd88'
down_revision = 'b61fe73ced1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
